# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hudobná skupina UNIX 
email: stuckajano6@gmail.com
description: "Sme hudobná skupina fungujúca v tomto zložení od roku 2016. Našou silnou stránkou sú piesne, ktoré hráme vždy naživo. V apríli roku 2018 sme vydali náš prvý album s názvom Slovenský chlap. Hráme svadby, plesy, zábavy, rodinné a firemné akcie, stužkové a mnoho ďalších."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://husar.github.io/demosite/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll 

# Build settings
markdown: kramdown

permalink: none
comments: true
defaults:
  -
    scope:
      path: "" # an empty string here  means all  files in the project 
      type: "posts" # previously 'post' in Jekyll 2.2.
    values:
      layout: "post"
      author: "Ján Štucka"
      category: "ukazky"

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
